
import javax.swing.JButton;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muy
 */
public class PrototypeD extends javax.swing.JFrame {
    private RotatedButton expandButton;
    private RotatedButton commitButton;
    private RotatedButton notificationButton;
    private RotatedButton issueButton;
    private String currDirectory;
    /**
     * Creates new form PrototypeD
     */
    public PrototypeD() {
        initComponents();
        initSidePanel();
        
    }
    
    private void initSidePanel()
    {
        textPanelLabel.setText("Commit History");
        expandButton = new RotatedButton("˅", false);
        commitButton = new RotatedButton("Commit", true);
        notificationButton = new RotatedButton("Notification", true);
        issueButton = new RotatedButton("Issue", true);
        sidePanel.add(expandButton);
        sidePanel.add(commitButton);
        sidePanel.add(notificationButton);
        sidePanel.add(issueButton);
        sidePanel.setVisible(true);
        
        expandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandButtonPerformed(evt);
            }
        });
        
        commitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtonPerformed(evt);
            }
        });
         
        notificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationButtonPerformed(evt);
            }
        });
        
        issueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueButtonPerformed(evt);
            }
        });

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CommandLinePane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Tabbed = new javax.swing.JTabbedPane();
        Local = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TreeViewButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Remote = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        textPanelInner = new javax.swing.JPanel();
        textPanelLabel = new javax.swing.JLabel();
        textArea = new javax.swing.JLayeredPane();
        stephenLabel = new javax.swing.JLabel();
        stephenDate = new javax.swing.JLabel();
        stephenTitle = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jiayiLabel = new javax.swing.JLabel();
        jiayiDate = new javax.swing.JLabel();
        jiayiTitle = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        muyLabel = new javax.swing.JLabel();
        muyDate = new javax.swing.JLabel();
        muyTitle = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        sarahTitle = new javax.swing.JLabel();
        sarahDate = new javax.swing.JLabel();
        sarahLabel = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        leoTitle = new javax.swing.JLabel();
        leoDate = new javax.swing.JLabel();
        leoLable = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        userName = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        fileOption = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        toolOption = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        helpOption = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CommandLinePane.setBackground(new java.awt.Color(204, 204, 204));
        CommandLinePane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("@User1:~$     |");

        javax.swing.GroupLayout CommandLinePaneLayout = new javax.swing.GroupLayout(CommandLinePane);
        CommandLinePane.setLayout(CommandLinePaneLayout);
        CommandLinePaneLayout.setHorizontalGroup(
            CommandLinePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandLinePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(878, Short.MAX_VALUE))
        );
        CommandLinePaneLayout.setVerticalGroup(
            CommandLinePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandLinePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(899, 439));
        jPanel1.setMinimumSize(new java.awt.Dimension(899, 439));

        Tabbed.setBackground(new java.awt.Color(204, 240, 240));
        Tabbed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("- Project3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("+ Project1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("+ Project2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("+ Master  Branch");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("+ Release Branch");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("! uncommited");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("! uncommited");

        TreeViewButton.setText("Tree View");

        jButton1.setText("Merge");

        javax.swing.GroupLayout LocalLayout = new javax.swing.GroupLayout(Local);
        Local.setLayout(LocalLayout);
        LocalLayout.setHorizontalGroup(
            LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LocalLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LocalLayout.createSequentialGroup()
                        .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LocalLayout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TreeViewButton)
                        .addGap(22, 22, 22))))
        );
        LocalLayout.setVerticalGroup(
            LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LocalLayout.createSequentialGroup()
                        .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TreeViewButton)
                            .addComponent(jButton1))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        Tabbed.addTab("Local", Local);

        Remote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remotePerformed(evt);
            }
        });

        javax.swing.GroupLayout RemoteLayout = new javax.swing.GroupLayout(Remote);
        Remote.setLayout(RemoteLayout);
        RemoteLayout.setHorizontalGroup(
            RemoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        RemoteLayout.setVerticalGroup(
            RemoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        Tabbed.addTab("Remote", Remote);

        textPanel.setBackground(new java.awt.Color(204, 204, 255));
        textPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textPanelInner.setBackground(new java.awt.Color(225, 225, 225));
        textPanelInner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textPanelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout textPanelInnerLayout = new javax.swing.GroupLayout(textPanelInner);
        textPanelInner.setLayout(textPanelInnerLayout);
        textPanelInnerLayout.setHorizontalGroup(
            textPanelInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPanelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        textPanelInnerLayout.setVerticalGroup(
            textPanelInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textPanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        textArea.setBackground(new java.awt.Color(204, 255, 255));

        stephenLabel.setText("○ Stephen");
        stephenLabel.setBounds(0, 0, 80, 14);
        textArea.add(stephenLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        stephenDate.setText("Date: 14/09/2013");
        stephenDate.setBounds(10, 20, 100, 14);
        textArea.add(stephenDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        stephenTitle.setText("Title: update friend list");
        stephenTitle.setBounds(10, 40, 160, 14);
        textArea.add(stephenTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator9.setBounds(0, 58, 220, 2);
        textArea.add(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jiayiLabel.setText("○ JiaYi");
        jiayiLabel.setBounds(0, 70, 70, 14);
        textArea.add(jiayiLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jiayiDate.setText("Date: 14/09/2013");
        jiayiDate.setBounds(10, 90, 110, 14);
        textArea.add(jiayiDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jiayiTitle.setText("Title: Update search ");
        jiayiTitle.setBounds(10, 110, 170, 14);
        textArea.add(jiayiTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator11.setBounds(0, 130, 220, 2);
        textArea.add(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        muyLabel.setText("○ Muy");
        muyLabel.setBounds(0, 140, 90, 14);
        textArea.add(muyLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        muyDate.setText("Date: 14/09/2013");
        muyDate.setBounds(10, 160, 110, 14);
        textArea.add(muyDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        muyTitle.setText("Title: Update database");
        muyTitle.setBounds(10, 180, 180, 14);
        textArea.add(muyTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator12.setBounds(0, 200, 220, 2);
        textArea.add(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sarahTitle.setText("Title: create database");
        sarahTitle.setBounds(10, 250, 180, 14);
        textArea.add(sarahTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sarahDate.setText("Date: 13/09/2013");
        sarahDate.setBounds(10, 230, 100, 14);
        textArea.add(sarahDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sarahLabel.setText("○ Sarah");
        sarahLabel.setBounds(0, 210, 100, 14);
        textArea.add(sarahLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator13.setBounds(0, 270, 220, 2);
        textArea.add(jSeparator13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leoTitle.setText("Title: Create friend list");
        leoTitle.setBounds(10, 320, 180, 14);
        textArea.add(leoTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leoDate.setText("Date: 12/09/2013");
        leoDate.setBounds(10, 300, 120, 14);
        textArea.add(leoDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        leoLable.setText("○ Leo");
        leoLable.setBounds(0, 280, 70, 14);
        textArea.add(leoLable, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textPanelInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addComponent(textPanelInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Tabbed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tabbed)
                    .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userName.setText("User1");
        userName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userName.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItem1.setText("Log Out");
        userName.add(jMenuItem1);

        jMenuItem2.setText("View Profile");
        userName.add(jMenuItem2);
        userName.add(jSeparator1);

        jMenuItem7.setText("Exit");
        userName.add(jMenuItem7);

        menuBar.add(userName);

        fileOption.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fileOption.setText("File");
        fileOption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fileOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileOption.setPreferredSize(new java.awt.Dimension(80, 40));

        jMenuItem3.setText("New Project");
        fileOption.add(jMenuItem3);

        jMenuItem4.setText("Load Project");
        fileOption.add(jMenuItem4);

        jMenuItem6.setText("New Branch");
        fileOption.add(jMenuItem6);

        jMenuItem15.setText("Load Branch");
        fileOption.add(jMenuItem15);

        menuBar.add(fileOption);

        toolOption.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolOption.setText("Tool");
        toolOption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toolOption.setHideActionText(true);
        toolOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toolOption.setPreferredSize(new java.awt.Dimension(80, 40));
        toolOption.setRequestFocusEnabled(false);

        jMenuItem5.setText("Show Teminal");
        toolOption.add(jMenuItem5);

        jMenuItem8.setText("Merge");
        toolOption.add(jMenuItem8);

        jMenuItem12.setText("Preference");
        toolOption.add(jMenuItem12);

        menuBar.add(toolOption);

        helpOption.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpOption.setText("Help");
        helpOption.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpOption.setPreferredSize(new java.awt.Dimension(80, 40));

        jMenuItem10.setText("Help Content");
        helpOption.add(jMenuItem10);

        jMenuItem11.setText("Online Help");
        helpOption.add(jMenuItem11);

        jMenuItem13.setText("Bug Report");
        helpOption.add(jMenuItem13);
        helpOption.add(jSeparator2);

        jMenuItem9.setText("About");
        helpOption.add(jMenuItem9);

        jMenuItem14.setText("Check For Update");
        helpOption.add(jMenuItem14);

        menuBar.add(helpOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CommandLinePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 445, Short.MAX_VALUE)
                    .addComponent(CommandLinePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remotePerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remotePerformed
        // TODO add your handling code here:
        currDirectory = new String("remote");
    }//GEN-LAST:event_remotePerformed

    private void expandButtonPerformed(java.awt.event.ActionEvent evt)
    {
        if (textPanel.isVisible())
        {
            textPanel.setVisible(false);
            expandButton.changeText("˄");
            Tabbed.setSize(850, 408);
        }
        else
        {
            textPanel.setVisible(true);
            expandButton.changeText("˅");
            Tabbed.setSize(620, 408);
        }
    }
    
    private void commitButtonPerformed(java.awt.event.ActionEvent evt)
    {
        textPanel.setVisible(true);
        expandButton.changeText("˅");
        textPanelLabel.setText("Commit History");
        stephenTitle.setText("Title: update friend list");
        jiayiTitle.setText("Title: Update search ");
        muyTitle.setText("Title: Update database");
        sarahTitle.setText("Title: create database");
        leoTitle.setText("Title: Create friend list");
    }
    
    private void notificationButtonPerformed(java.awt.event.ActionEvent evt)
    {
        textPanel.setVisible(true);
        expandButton.changeText("˅");
        textPanelLabel.setText("Notification");
        stephenTitle.setText("Title: friend list");
        jiayiTitle.setText("Title: Implementing search ");
        muyTitle.setText("Title: change database password");
        sarahTitle.setText("Title: create database");
        leoTitle.setText("Title: friend list changed");
    }
    
    private void issueButtonPerformed(java.awt.event.ActionEvent evt)
    {
        textPanel.setVisible(true);
        expandButton.changeText("˅");
        textPanelLabel.setText("Issue");
        stephenTitle.setText("Title: cannot integrate");
        jiayiTitle.setText("Title: laptop not working");
        muyTitle.setText("Title: database not working");
        sarahTitle.setText("Title: database not set up");
        leoTitle.setText("Title: new gui breaks");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrototypeD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrototypeD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrototypeD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrototypeD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrototypeD().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CommandLinePane;
    private javax.swing.JPanel Local;
    private javax.swing.JPanel Remote;
    private javax.swing.JTabbedPane Tabbed;
    private javax.swing.JButton TreeViewButton;
    private javax.swing.JMenu fileOption;
    private javax.swing.JMenu helpOption;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jiayiDate;
    private javax.swing.JLabel jiayiLabel;
    private javax.swing.JLabel jiayiTitle;
    private javax.swing.JLabel leoDate;
    private javax.swing.JLabel leoLable;
    private javax.swing.JLabel leoTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel muyDate;
    private javax.swing.JLabel muyLabel;
    private javax.swing.JLabel muyTitle;
    private javax.swing.JLabel sarahDate;
    private javax.swing.JLabel sarahLabel;
    private javax.swing.JLabel sarahTitle;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel stephenDate;
    private javax.swing.JLabel stephenLabel;
    private javax.swing.JLabel stephenTitle;
    private javax.swing.JLayeredPane textArea;
    private javax.swing.JPanel textPanel;
    private javax.swing.JPanel textPanelInner;
    private javax.swing.JLabel textPanelLabel;
    private javax.swing.JMenu toolOption;
    private javax.swing.JMenu userName;
    // End of variables declaration//GEN-END:variables

}
